### ISSUE TITLE
Merge comment doesn't work anymore

### ISSUE THREAD

**Issue by adngdb** [mozilla/rob-bugson#23]
I see the last issue here was about the same problem. I guess GitHub did it again? Anyway, after I merge a pull request, I don't get the "Add merge comment to bug" link to show up anymore. It makes me very sad! :cry:

**Comment by adngdb** [comment]
Screenshot: 

![Screenshot_2019-09-30 Fix bug 1584226 - Redirect to current translate page is Translate Nex… by adngdb · Pull Request #1402](https://user-images.githubusercontent.com/328790/65896925-7481f780-e3ae-11e9-9a9b-da1a4de47b9b.png)

**Comment by willkg** [comment]
If the bug number shows up in the "attach this PR ..." list, it should show up in the "Add merge comment to ..." list. I'm pretty sure they're generated in the same way.

I'm not sure what might be happening here. That's puzzling.

What's the url for the PR you're having problems with?

**Comment by willkg** [comment]
Nevermind--I can reproduce it, too.

It worked fine last week. I'm not sure what's going on. I'll look into it.

**Comment by willkg** [comment]
I fixed it and pushed 1.6.1. Once that's approved on AMO, you can update and it should work again.

Sorry about that!

**Comment by adngdb** [comment]
It's fixed! Thank you very much! 

![](https://media.giphy.com/media/3oEjHV0z8S7WM4MwnK/giphy.gif)
