### ISSUE TITLE
merge link doesn't show up if you're using Refined GitHub

### ISSUE THREAD

**Issue by willkg** [mozilla/rob-bugson#32]
If you're using Refined GitHub, then the merge link doesn't show up.

https://addons.mozilla.org/en-US/firefox/addon/refined-github-/

**Comment by willkg** [comment]
Here's what you see with Refined Github:

![image](https://user-images.githubusercontent.com/820826/186213034-44fb073f-4920-4a34-a7af-d15cec739b88.png)

It's probably the case that the HTML around the "Merged" changed enough that rob-bugson doesn't recognize it.

**Comment by badboy** [comment]
`TypeError: can't access property "getAttribute", commitElem is null}`

finally caught what's going on.

**Comment by willkg** [comment]
I released this just now in v1.6.4. Thank you for fixing it--I really appreciate it!
