### ISSUE TITLE
Auto-fill breaks if the attachment page defaults to a file upload

### ISSUE THREAD

**Issue by Osmose** [mozilla/rob-bugson#4]
If the last attachment you uploaded was a file upload, the attachment page doesn't have the textbox to enter the Github link into, and auto-fill fails.

**Comment by willkg** [comment]
That should be covered by this code here:

https://github.com/willkg/rob-bugson/blob/master/github-pr-background.js#L47

Any idea why that might be failing?

**Comment by Osmose** [comment]
Here's a screenshot of my browser console when I replicate the behavior:

<img width="799" alt="screen shot 2017-10-24 at 11 14 47 am" src="https://user-images.githubusercontent.com/193106/31960430-a0c8f296-b8ac-11e7-82eb-66a57f64dbf9.png">

**Comment by willkg** [comment]
That screenshot helped a ton. I'll look into this now.
